"""
feed.bootstrap — detect_repo_state + bootstrap_first_friend + clone_existing.

Real implementation (task #21). Replaces scaffold stubs from task #17.

This module owns the Stage 3 contract that onboarding-2's /sf:install consumes.

Per plan §5.1 decision tree (lead-approved):

    INPUT: repo_url, local_path (defaults to feed.config.local_path())

    1. local_path exists AND has .git pointing at repo_url?
       YES → mode = 'already-cloned'; existing_handles = scan *.log.md basenames
       NO  → continue

    2. `gh repo view <repo_url> --json visibility` → repo exists?
       NO  → mode = 'first-friend-bootstrap'
       YES → continue

    3. `gh api repos/<owner>/<repo>/contents/` → any *.log.md files at root?
       NO  → mode = 'first-friend-bootstrap' (repo pre-created but empty)
       YES → mode = 'joiner-clone'; existing_handles = strip '.log.md' basenames

Per team-lead pushback (2026-05-28): step 2 may surface auth errors. We surface them
cleanly via `auth_error` attribute on the returned RepoState so the caller can re-run
check_auth() and remediate.

bootstrap_first_friend + clone_existing are graceful-degradation-friendly: local-only
work (git init / git clone) always tries to complete; remote push is best-effort and
queues on failure (uses feed.io_github.push).
"""

from __future__ import annotations

import json
import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal, Optional

from feed import config, io_github
from feed.writer import SCHEMA_HEADER_TEMPLATE


RepoMode = Literal["first-friend-bootstrap", "joiner-clone", "already-cloned"]


@dataclass(frozen=True)
class RepoState:
    """Return shape of feed_detect_repo_state.

    `local_path`: filesystem path where the activity-feed clone lives or will live.
    Owned by feed (per team-lead); exposed via this field so onboarding doesn't need
    to know the path convention.

    `auth_error`: when set, indicates `gh repo view` failed with what looks like an
    auth error. Caller (onboarding Stage 3) should re-run `feed.check_auth()` and
    remediate before retrying detect.
    """

    mode: RepoMode
    has_other_friends: bool
    existing_handles: tuple[str, ...]
    needs_init: bool
    local_path: Path
    auth_error: Optional[str] = None
    detection_notes: tuple[str, ...] = ()
    """Diagnostic notes about why we picked this mode. Useful for /sf:doctor /
    onboarding's verbose-mode output. Free-form strings."""


README_BOOTSTRAP_TEMPLATE = """\
# Friend-group Activity Feed

This repo is the **Activity Feed** for our friend group — a thin, append-only log
of what each friend's Claude is doing at session boundaries. Per ADR-018.

## What's in here

- `<handle>.log.md` — one file per friend. Each friend writes only to their own file.
  Entries follow the terse format: `## [YYYY-MM-DD HH:MM] start|end | <handle> | <desc>`.
- `identities/<handle>.md` — public-facing identity per friend (display name, role,
  optional contact pref). Friends author their own; other friends read.
- This `README.md`.

## How it stays clean

- **No code, no decisions, no transcripts in entries.** Per ADR-021: the terse format
  IS the privacy mechanism. Session summaries are 1-2 sentences + file list.
- **Per-friend files** prevent merge conflicts when multiple friends close sessions
  simultaneously.
- **Auto-push by hooks**, not by humans. Sessions write themselves; you don't.

## Opt-out

- `/sf:wrap --skip-feed` — skip a single session-end push
- `SF_SKIP_FEED=1` — skip a whole session (process-tree env var)
- `/sf:disable-feed` — kill switch for the current session (start AND end)

For a deeper friend-facing explainer (privacy model, what gets shared vs. stays
local, common questions), see `ACTIVITY_FEED.md` in your installed framework's
`docs/` directory — or ask your group's maintainer if you can't find it.

## What this is NOT

- Not a messaging tool (use WhatsApp/Discord)
- Not a shared wiki (wikis are per-friend-local per ADR-017)
- Not a place to drop files, attach screenshots, or hold conversations

## Generated by the startup framework

This repo's structure is owned by the `sf-feed` module. Don't hand-edit unless you
know what you're doing — the framework expects `<handle>.log.md` files at the root
with file-top YAML frontmatter (`schema_version: 1`, `type: feed-entry`, `handle: ...`).
Hand-edits that break those invariants will trigger schema-mismatch errors on the
next write.
"""


IDENTITY_PLACEHOLDER_TEMPLATE = """\
---
handle: {handle}
name: ""
phase: ""
strong_skills: []
clouds: []
---

# {handle}

_Placeholder identity file — onboarding's `/sf:interview` (Stage 4) will fill in the
real content via `feed.feed_upsert_identity`._
"""


# --- public API -------------------------------------------------------------


def feed_detect_repo_state(
    repo_url: str,
    local_path: Path | str | None = None,
) -> RepoState:
    """Detect whether onboarding should bootstrap-as-first-friend or clone-as-joiner.

    Decision tree per plan §5.1.

    Args:
        repo_url: e.g., "friend-group/activity-feed" or full GitHub URL
        local_path: optional override of clone destination

    Returns:
        RepoState with mode + metadata. Onboarding branches on `mode`:
        - 'first-friend-bootstrap' → call feed_bootstrap_first_friend(...)
        - 'joiner-clone'           → call feed_clone_existing(...)
        - 'already-cloned'         → skip (idempotent re-install)

    Auth errors from `gh repo view` are surfaced via RepoState.auth_error.
    """
    if local_path is None:
        path = config.local_path()
    else:
        path = Path(local_path)

    notes: list[str] = []

    # --- Step 1: already-cloned? ---
    if _is_cloned_repo_pointing_at(path, repo_url):
        notes.append(f"local clone at {path} already points at {repo_url}")
        handles = _scan_existing_handles(path)
        return RepoState(
            mode="already-cloned",
            has_other_friends=any(h for h in handles),
            existing_handles=handles,
            needs_init=False,
            local_path=path,
            detection_notes=tuple(notes),
        )
    notes.append(f"no existing clone at {path}")

    # --- Step 2: does the remote repo exist? ---
    repo_exists, auth_error = _remote_repo_exists(repo_url)
    if auth_error is not None:
        # Caller is responsible for re-running check_auth() + remediating, then
        # retrying detect. We return early with the auth_error populated.
        notes.append(f"gh repo view surfaced auth error: {auth_error}")
        return RepoState(
            mode="first-friend-bootstrap",  # placeholder; caller should re-run after auth fix
            has_other_friends=False,
            existing_handles=(),
            needs_init=True,
            local_path=path,
            auth_error=auth_error,
            detection_notes=tuple(notes),
        )
    if not repo_exists:
        notes.append(f"repo {repo_url} does not exist on GitHub yet")
        return RepoState(
            mode="first-friend-bootstrap",
            has_other_friends=False,
            existing_handles=(),
            needs_init=True,
            local_path=path,
            detection_notes=tuple(notes),
        )
    notes.append(f"repo {repo_url} exists on GitHub")

    # --- Step 3: any *.log.md files at root? ---
    existing_handles = _remote_log_handles(repo_url)
    if not existing_handles:
        notes.append("repo is empty (no *.log.md files) — first-friend-bootstrap")
        return RepoState(
            mode="first-friend-bootstrap",
            has_other_friends=False,
            existing_handles=(),
            needs_init=True,
            local_path=path,
            detection_notes=tuple(notes),
        )
    notes.append(f"repo has existing handles: {', '.join(existing_handles)}")
    return RepoState(
        mode="joiner-clone",
        has_other_friends=True,
        existing_handles=existing_handles,
        needs_init=False,
        local_path=path,
        detection_notes=tuple(notes),
    )


def feed_bootstrap_first_friend(
    local_path: Path | str,
    handle: str,
    repo_url: str,
) -> None:
    """Initialize the activity-feed repo as the first friend.

    - git init local_path
    - git remote add origin <repo_url>
    - Write README.md from template
    - Write <handle>.log.md with file-top YAML frontmatter
    - Write identities/<handle>.md placeholder
    - git add + commit + push (best-effort; queues on failure)

    Raises subprocess.CalledProcessError on local git init failure; never raises on
    remote-push failures (handled by feed.io_github.push graceful degradation).
    """
    path = Path(local_path)
    path.mkdir(parents=True, exist_ok=True)

    # git init (idempotent if .git already exists)
    if not (path / ".git").exists():
        subprocess.run(["git", "init", "-q", str(path)], check=True)
        subprocess.run(
            ["git", "-C", str(path), "branch", "-M", "main"], check=False
        )  # OK if it fails (e.g., no commits yet)

    # git remote add origin (idempotent — set-url if already exists)
    existing = subprocess.run(
        ["git", "-C", str(path), "remote", "get-url", "origin"],
        capture_output=True, text=True,
    )
    if existing.returncode != 0:
        subprocess.run(
            ["git", "-C", str(path), "remote", "add", "origin", _normalize_remote_url(repo_url)],
            check=True,
        )

    _write_bootstrap_files(path, handle)

    # Push (best-effort)
    io_github.push(commit_msg=f"{handle} bootstrap (first friend)")


def feed_clone_existing(
    repo_url: str,
    local_path: Path | str,
    handle: str,
) -> None:
    """Clone an existing activity-feed repo as a joiner.

    - gh repo clone <repo_url> <local_path>
    - Verify own <handle>.log.md does NOT already exist (caller handles collision)
    - Create own <handle>.log.md with frontmatter
    - Create own identities/<handle>.md placeholder
    - git add + commit + push (best-effort)

    Raises FileExistsError if the local_path already has a <handle>.log.md (collision).
    Raises subprocess.CalledProcessError on clone failure.
    """
    path = Path(local_path)

    # Clone (gh handles auth + correct URL form)
    if not (path / ".git").exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        subprocess.run(
            ["gh", "repo", "clone", repo_url, str(path)], check=True,
        )

    # Collision check
    own_log = path / f"{handle}.log.md"
    if own_log.exists():
        raise FileExistsError(
            f"{own_log} already exists. Pick a different handle (existing: "
            f"{', '.join(_scan_existing_handles(path))})"
        )

    _write_bootstrap_files(path, handle, skip_readme=True)

    # Push the new files (best-effort)
    io_github.push(commit_msg=f"{handle} joins the friend group")


# --- helpers ---------------------------------------------------------------


def _is_cloned_repo_pointing_at(path: Path, repo_url: str) -> bool:
    """True if `path/.git` exists and `origin` points at `repo_url`."""
    if not (path / ".git").exists():
        return False
    result = subprocess.run(
        ["git", "-C", str(path), "remote", "get-url", "origin"],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        return False
    actual = result.stdout.strip()
    return _remotes_equivalent(actual, repo_url)


def _remotes_equivalent(a: str, b: str) -> bool:
    """True if two remote URLs refer to the same GitHub repo, ignoring URL form.

    Accepts variations: https://, git@github.com:, ssh://, with-or-without .git suffix,
    with-or-without trailing slash, with-or-without github.com prefix on shorthand.
    """
    return _canonical_repo_id(a) == _canonical_repo_id(b)


def _canonical_repo_id(url: str) -> str:
    """Reduce a repo URL to canonical 'owner/repo' lowercase form."""
    url = url.strip().rstrip("/")
    if url.endswith(".git"):
        url = url[:-4]
    # SSH form: git@github.com:owner/repo
    m = re.match(r"^git@github\.com:(.+)$", url)
    if m:
        return m.group(1).lower()
    # HTTPS/SSH protocol: https://github.com/owner/repo or ssh://git@github.com/...
    m = re.match(r"^(?:https?|ssh|git)://(?:[^/]+@)?github\.com/(.+)$", url)
    if m:
        return m.group(1).lower()
    # Shorthand: owner/repo
    return url.lower()


def _normalize_remote_url(repo_url: str) -> str:
    """Expand shorthand 'owner/repo' to full https URL for git remote add."""
    if "://" in repo_url or repo_url.startswith("git@"):
        return repo_url
    # shorthand
    return f"https://github.com/{repo_url}.git"


def _remote_repo_exists(repo_url: str) -> tuple[bool, Optional[str]]:
    """Returns (exists, auth_error). On auth failure, returns (False, error_str)."""
    canonical = _canonical_repo_id(repo_url)
    try:
        result = subprocess.run(
            ["gh", "repo", "view", canonical, "--json", "name,visibility"],
            capture_output=True, text=True, timeout=10,
        )
    except FileNotFoundError:
        return False, "gh CLI not installed"
    except subprocess.TimeoutExpired:
        return False, "gh repo view timed out"

    if result.returncode == 0:
        return True, None

    stderr = result.stderr.lower()
    if "not found" in stderr or "could not resolve" in stderr or "404" in stderr:
        return False, None  # repo just doesn't exist; not an auth error
    if any(token in stderr for token in ("authentication", "unauthorized", "401", "403", "log in")):
        return False, result.stderr.strip()
    # Unknown error — surface as auth_error so caller investigates
    return False, result.stderr.strip() or "unknown gh repo view error"


def _remote_log_handles(repo_url: str) -> tuple[str, ...]:
    """Return tuple of existing handles by listing root .log.md files via gh api."""
    canonical = _canonical_repo_id(repo_url)
    try:
        result = subprocess.run(
            ["gh", "api", f"repos/{canonical}/contents/", "--jq",
             "[.[] | select(.type==\"file\" and (.name|endswith(\".log.md\"))) | .name]"],
            capture_output=True, text=True, timeout=10,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return ()

    if result.returncode != 0:
        return ()

    try:
        names = json.loads(result.stdout)
    except json.JSONDecodeError:
        return ()

    # Defense-in-depth filter: even though our --jq narrows to .log.md, defend
    # against jq absence (older gh versions) or filter changes by filtering again here.
    return tuple(
        name.removesuffix(".log.md")
        for name in names
        if isinstance(name, str) and name.endswith(".log.md")
    )


def _scan_existing_handles(local_path: Path) -> tuple[str, ...]:
    """Scan a local clone for existing <handle>.log.md files."""
    if not local_path.exists():
        return ()
    return tuple(
        sorted(p.stem.removesuffix(".log") for p in local_path.glob("*.log.md"))
    )


def _write_bootstrap_files(path: Path, handle: str, *, skip_readme: bool = False) -> None:
    """Write README.md (optional) + <handle>.log.md frontmatter + identities/<handle>.md placeholder."""
    if not skip_readme:
        readme = path / "README.md"
        if not readme.exists():
            readme.write_text(README_BOOTSTRAP_TEMPLATE, encoding="utf-8")

    log_file = path / f"{handle}.log.md"
    if not log_file.exists():
        header = SCHEMA_HEADER_TEMPLATE.format(
            version=config.EXPECTED_FEED_SCHEMA_VERSION,
            framework_version=config.framework_version(),
            handle=handle,
        )
        log_file.write_text(header, encoding="utf-8")

    identities_dir = path / "identities"
    identities_dir.mkdir(parents=True, exist_ok=True)
    id_file = identities_dir / f"{handle}.md"
    if not id_file.exists():
        id_file.write_text(
            IDENTITY_PLACEHOLDER_TEMPLATE.format(handle=handle), encoding="utf-8"
        )
