"""
sf-wrap local types.

Pure dataclasses for the /sf:wrap pipeline. No I/O, no external deps beyond
stdlib + typing. Frozen by default per dotfiles python/coding-style.md
(immutability principle from common/coding-style.md).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Literal


SignalLabel = Literal[
    "none",
    "decision",
    "pattern",
    "lesson",
    "stack_change",
    "milestone",
    "purpose_shift",
]


class DiffKind(str, Enum):
    """How a wiki page is being changed in the diff plan."""

    CREATE = "create"
    EDIT = "edit"
    APPEND = "append"


@dataclass(frozen=True)
class ClassifierResult:
    """
    The output of the signal-threshold classifier (per
    references/signal-threshold.md).
    """

    labels: tuple[SignalLabel, ...]
    reasoning: str
    candidate_artifacts: tuple["CandidateArtifact", ...] = ()

    @property
    def has_signal(self) -> bool:
        """True if any label other than `none` fired."""
        return any(label != "none" for label in self.labels)


@dataclass(frozen=True)
class CandidateArtifact:
    """
    A proposed wiki artifact to create/edit based on a classifier signal.
    Per references/signal-threshold.md classifier prompt template.
    """

    label: SignalLabel
    proposed_title: str  # kebab-case slug
    proposed_summary: str  # ≤300 chars (matches feed terse cap for consistency)
    target_file: str  # relative wiki path


@dataclass(frozen=True)
class DiffEntry:
    """
    One concrete change to apply to a wiki file. Generated by the diff
    planner from a CandidateArtifact + the current wiki state.
    """

    target_file: str  # absolute path under ~/.startup-framework/wiki/
    kind: DiffKind
    unified_diff: str  # text in unified-diff format (compatible with git apply)
    rationale: str  # short justification shown to the user


@dataclass(frozen=True)
class DiffPlan:
    """A batch of diffs to apply atomically."""

    entries: tuple[DiffEntry, ...]
    context_md_rewrite: str  # the new CONTEXT.md content; always present


@dataclass(frozen=True)
class WrapInputs:
    """All inputs gathered for a /sf:wrap invocation."""

    session_transcript_path: str | None
    session_notes: tuple[str, ...]  # contents of /sf:note pin file(s)
    cwd: str
    active_project: str | None
    skip_feed_flag: bool  # from --skip-feed CLI arg


@dataclass(frozen=True)
class WrapResult:
    """
    Final result returned to the user after /sf:wrap completes. The user-
    facing summary is composed from this.
    """

    wiki_pages_changed: tuple[str, ...]  # paths actually written
    wiki_pages_skipped: tuple[str, ...]  # proposed but user rejected
    feed_write_attempted: bool
    feed_write_success: bool
    feed_write_queued: bool
    feed_write_violation: str | None
    feed_write_error: str | None
    context_md_path: str
    next_session_pointer: str  # first ~100 chars of new CONTEXT.md content
    elapsed_seconds: float

    @property
    def had_signal(self) -> bool:
        return len(self.wiki_pages_changed) > 0 or len(self.wiki_pages_skipped) > 0


@dataclass(frozen=True)
class FormatViolationReport:
    """Result of pre-validating a task_brief before calling feed."""

    valid: bool
    reason: str | None = None  # e.g. "summary contains triple-backtick fence"

    def __bool__(self) -> bool:
        return self.valid
